///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace chessBot
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the chessBotRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("4282da7f-35b6-4727-9d35-7f7655db4635")]
    public partial class chessBotRepository : RepoGenBaseFolder
    {
        static chessBotRepository instance = new chessBotRepository();

        /// <summary>
        /// Gets the singleton class instance representing the chessBotRepository element repository.
        /// </summary>
        [RepositoryFolder("4282da7f-35b6-4727-9d35-7f7655db4635")]
        public static chessBotRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public chessBotRepository() 
            : base("chessBotRepository", "/", null, 0, false, "4282da7f-35b6-4727-9d35-7f7655db4635", ".\\RepositoryImages\\chessBotRepository4282da7f.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4282da7f-35b6-4727-9d35-7f7655db4635")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class chessBotRepositoryFolders
    {
    }
#pragma warning restore 0436
}